version: "2"
services: 
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD="secret"
  web:
   image: apache
   build: ./webapps
   depends_on:
      - db
   container_name: apache_web
   restart: always
   ports:
     - "80:80"

